name: Deploy Website to All-Inkl

on:
  push:
    branches:
      - main # ODER master - je nachdem wie dein Haupt-Branch heißt

jobs:
  web-deploy:
    name: 🎉 Deploy HTML Files
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync HTML/CSS straight to All-Inkl
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # Da es reines HTML ist, laden wir das gesamte Hauptverzeichnis hoch
        local-dir: ./ 
        server-dir: ./
        # Verhindert, dass die GitHub-internen Ordner auf deinen Webspace geladen werden
        exclude: |
          **/.git*
          **/.git*/**
